git clone https://github.com/DistributedCollective/Sovryn
git clone https://github.com/DistributedCollective/Sovryn-Node-Monitor
git clone https://github.com/DistributedCollective/Sovryn-Admin-Panel
git clone https://github.com/DistributedCollective/Sovryn-website
git clone https://github.com/DistributedCollective/Fast-BTC-old
git clone https://github.com/DistributedCollective/SovrynEarlyAccess
git clone https://github.com/DistributedCollective/sovryn-faucet
git clone https://github.com/DistributedCollective/BNS-suite
git clone https://github.com/DistributedCollective/sovryn-mail-service-backend
git clone https://github.com/DistributedCollective/Sovryn-database
git clone https://github.com/DistributedCollective/Genesis-Sale-BTC
git clone https://github.com/DistributedCollective/Genesis-Sale-Frontend
git clone https://github.com/DistributedCollective/btc-predeposit-page
git clone https://github.com/DistributedCollective/sovryn-devops
git clone https://github.com/DistributedCollective/verify-vesting
git clone https://github.com/DistributedCollective/bug-reports
git clone https://github.com/DistributedCollective/sovryn-price-floor
git clone https://github.com/DistributedCollective/charting-library
git clone https://github.com/DistributedCollective/ETH-aggregator
git clone https://github.com/DistributedCollective/waterfall
git clone https://github.com/DistributedCollective/k8s-boilerplate-8
git clone https://github.com/DistributedCollective/Wiki-docs
git clone https://github.com/DistributedCollective/sovryn-arbitrage-watchers
git clone https://github.com/DistributedCollective/sovryn-perpetual
git clone https://github.com/DistributedCollective/sovryn-perpetual-swap
git clone https://github.com/DistributedCollective/Sovryn-tasks-discussions
git clone https://github.com/DistributedCollective/evmctl
git clone https://github.com/DistributedCollective/sovryn-margincall-service
git clone https://github.com/DistributedCollective/sovryn-notification-service
git clone https://github.com/DistributedCollective/sovryn-apy-service
git clone https://github.com/DistributedCollective/Sovryn-Datafeed
git clone https://github.com/DistributedCollective/price-variance-tracker
git clone https://github.com/DistributedCollective/amm-apy-calculator
git clone https://github.com/DistributedCollective/Sovryn-treasury-dashboard-service
git clone https://github.com/DistributedCollective/k8s-boilerplate-single-service
git clone https://github.com/DistributedCollective/Sovryn-treasury-dashboard-service-alt
git clone https://github.com/DistributedCollective/PerpetualSimulation
git clone https://github.com/DistributedCollective/sovryn-UI-automation-test
git clone https://github.com/DistributedCollective/Sovryn-margin-call
git clone https://github.com/DistributedCollective/tenderly-proxy-service
git clone https://github.com/DistributedCollective/sovryn-perp-swaps-backend
git clone https://github.com/DistributedCollective/Sovryn-perpetual-swaps-subgraph
git clone https://github.com/DistributedCollective/sovryn-perp-utils
git clone https://github.com/DistributedCollective/sovryn-continuous-token-subgraph
git clone https://github.com/DistributedCollective/internal-documentation
git clone https://github.com/DistributedCollective/bidirectional-fastbtc-deployment
git clone https://github.com/DistributedCollective/Sovryn-limit-order-routes
git clone https://github.com/DistributedCollective/Sovryn-access-controls
git clone https://github.com/DistributedCollective/sovryn-perps-arbitrage
git clone https://github.com/DistributedCollective/SIPSPrivate
git clone https://github.com/DistributedCollective/Sovryn-maintenance-mode-service
git clone https://github.com/DistributedCollective/sovryn-loan-risk
git clone https://github.com/DistributedCollective/solidity-hardhat-boilerplate
git clone https://github.com/DistributedCollective/sovryn-user-log
git clone https://github.com/DistributedCollective/sovryn-perpetuals-risk
git clone https://github.com/DistributedCollective/sovryn-infrastructure
git clone https://github.com/DistributedCollective/Watcher-arb
git clone https://github.com/DistributedCollective/Sovryn-api-gateway
git clone https://github.com/DistributedCollective/bridge-private
git clone https://github.com/DistributedCollective/twilio-poc
git clone https://github.com/DistributedCollective/sovryn-internal-notification-service
git clone https://github.com/DistributedCollective/forta-bots
git clone https://github.com/DistributedCollective/Sovryn_Predictor
git clone https://github.com/DistributedCollective/sovryn-amm-price-monitor
git clone https://github.com/DistributedCollective/sovryn-balance-monitor
git clone https://github.com/DistributedCollective/sovryn-vp-monitor
git clone https://github.com/DistributedCollective/sovryn-zero-user-alerts
git clone https://github.com/DistributedCollective/email-templates
git clone https://github.com/DistributedCollective/QA
git clone https://github.com/DistributedCollective/Mynt-subgraph
git clone https://github.com/DistributedCollective/sov-recent-events-wrapper
git clone https://github.com/DistributedCollective/sovryn-cloudflare
git clone https://github.com/DistributedCollective/sov-side-token-monitor
git clone https://github.com/DistributedCollective/sov-bridge-tx-monitor
git clone https://github.com/DistributedCollective/zero-sp-gains
git clone https://github.com/DistributedCollective/Subgraph-template
git clone https://github.com/DistributedCollective/JKDashboard_v3_2023_04_03
git clone https://github.com/DistributedCollective/sov-itoken-monitor
git clone https://github.com/DistributedCollective/BackendDocs
git clone https://github.com/DistributedCollective/multichain-integration
git clone https://github.com/DistributedCollective/sov-rsk-internal-access
git clone https://github.com/DistributedCollective/web-stablehodl
git clone https://github.com/DistributedCollective/nbte-bridge-prototype
git clone https://github.com/DistributedCollective/mynt-private
git clone https://github.com/DistributedCollective/zero-contracts-private
git clone https://github.com/DistributedCollective/testnet-rollup-bridge
git clone https://github.com/DistributedCollective/prototype-nbte-bridge
git clone https://github.com/DistributedCollective/nbte-bridge
git clone https://github.com/DistributedCollective/Ambient-DEX
git clone https://github.com/DistributedCollective/sovryn-bob-liquidity
git clone https://github.com/DistributedCollective/merkle-distributor
